/**
 * Utility to download content as a file.
 * Used by the frontend to save the XML generated by the server.
 */
export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// NOTE:
// The previous client-side parsing functions (parseOCRText, generateCSV, generateXML)
// have been removed. The parsing logic has been moved to the server-side
// using Google Gemini for higher accuracy and reliability.